name = "seatalk-bot"
main = "index.js"
compatibility_date = "2026-06-05"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "BOT_MEMORY"
id = "003dd4edcd8a4a8d96699c7cded27a39"

# TAMBAHAN PENTING UNTUK CRON SCHEDULER
# Ini membuat fungsi scheduled() di index.js berjalan setiap 1 menit.
[triggers]
crons = ["* * * * *"]
```