name = "seatalk-bot"
main = "index.js"
compatibility_date = "2026-06-05"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "BOT_MEMORY"
id = "003dd4edcd8a4a8d96699c7cded27a39"

[triggers]
crons = ["* * * * *"]

[vars]
GOOGLE_CLIENT_EMAIL = "vasa-725@studio-1196053014-a94d0.iam.gserviceaccount.com"
SEATALK_APP_ID = "NzE2Mjg3ODUxMjc5"
SEATALK_APP_SECRET = "<SET_IN_ENV>"
GITHUB_TRIGGER_TOKEN = "<SET_IN_ENV>"
GITHUB_REPOSITORY = "bp-pratama/seatalk_bot"
